- name: DTP configuration 
  hosts: "{{ switch }}"
  gather_facts: no
  tasks:
     - name: access port 
       ios_config:
         lines:
         - switchport mode acc
         parents: "{{ item }}"
       loop: "{{ interface }}"
