- name: EIGRP 
  hosts: router
  gather_facts: no
  tasks:
     - name: key chain configuration
       ios_config:
         lines:
         - key 1
         - key-string cisco
         before: key chain mychain
     - name: Authentication
       ios_config:
         lines:
         - ip auth mode eig 1 md5
         - ip auth key-chain eigrp 1 mychain  
         parents: "{{ item }}"
       loop: "{{ interface }}" 
