- name: eigrp defense play
  hosts: all
  gather_facts: no
  
  tasks:
    - name: task1
      ios_config:
        lines: passive-interface {{ item }}
        parents: router eigrp 1 
      loop: "{{ interface }}"
