- name: STP root guard 
  hosts: switch
  gather_facts: no 
  tasks: 
     - name: root guard configuration
       ios_config:
          lines: 
            - sp guard root 
          parents: int e0/1 
