- name: test
  hosts: all
  gather_facts: no

#  vars_prompt:
#    - name: interface
#      prompt: " your interface"
#      private: no
  
  tasks:
#    - set_fact:
#        interface_list: "{{ interface.split(',') }}"
 
#    - debug: 
#        msg: "{{item}}"
#      loop: "{{interface_list}}" 
    - name: test task1
      ios_config:
         lines:
         - description bbb
         parents: "{{interface}}"
#         parents: "{{item}}"
#      loop: "{{interface_list}}"
