- name: test
  hosts: switch
  gather_facts: no

  
  tasks:
    - name: test task1
      ios_config:
        lines:
        - description bbb
        parents: "{{ item }}"
      loop: "{{ interface }}"
