- name: test
  hosts: switch
  gather_facts: no

  
  tasks:
#    - set_fact:
#        interface_list: "{{ interface.split(',') }}"
 
#    - debug: 
#        msg: "{{item}}"
#      loop: "{{interface_list}}" 
    - name: test task1
      ios_config:
         lines:
         - description bbb
         parents: "{{interface}}"
#         parents: "{{item}}"
#      loop: "{{interface_list}}"
